### ISSUE TITLE
ngJsonEditor' is not available

### ISSUE THREAD

**Issue by c0debreaker** [bastiendonjon/angular-jsoneditor#1]
I loaded the module but when I start my angular Application, I'm getting this error.

Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngJsonEditor due to:
Error: [$injector:nomod] Module 'ngJsonEditor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Inside my bower.json file, I have this under dependencies

"jsoneditor": "~4.2.0"

**Comment by bastiendonjon** [comment]
You have edited your html tag head ? to add "angular-jsoneditor.js"

**Comment by c0debreaker** [comment]
Maybe gulp didn't include it. I'll add it manually. Thanks.

**Comment by bastiendonjon** [comment]
You have fixed your problem ?

**Comment by c0debreaker** [comment]
The design team changed our website design. The bosses didnt' like the json editor idea.
